from .pycopterui import Ui_pycopter
from pycopter.xfoil import ensure_airfoil_coordinates, is_naca_airfoil, normalize_airfoil_name

class InputChecker():
    """
    Spawn this class and use its functions to check GUI inputs. Functions return False if an issue was detected.
    In that case, property 'error_message' carries the reason. 

    In initial version, error checker is only implemented for a UI.

    Methods
    -------
    airfoil_checker() -> bool
        Checks the airfoil string input for correctness and returns True.
    """
    def __init__(self, ui: Ui_pycopter):
        """Pass in UI that contains the user inputs.
        
        Parameters
        ----------
        ui : PyQt UI class generated by pyuic5
        """
        self.ui = ui
        
        self.error_message = "" # If functions return false, print this on the interface.

    def airfoil_checker(self):
        """Checks airfoil input and returns False if an issue was detected."""
        airfoil = normalize_airfoil_name(self.ui.airfoilText.toPlainText())

        if not airfoil:
            self.error_message = "ERROR - Airfoil must not be empty."
            return False

        if is_naca_airfoil(airfoil):
            return True

        if airfoil.startswith("naca"):
            self.error_message = "ERROR - Invalid NACA airfoil. Only 4, 5, and 6 digit NACA profiles are supported."
            return False

        success, _, message = ensure_airfoil_coordinates(airfoil)
        if not success:
            self.error_message = f"ERROR - {message}"
            return False
        
        return True
